name: deploy backend to GCS
on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]
jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read  # Allow reading the repository contents
            id-token: write  # Allow generating an ID token for GCP authentication
        steps:

            # 0 Checkout code
            - uses: actions/checkout@v4

            # 1. Set up legacy authentication for GCP using JSON key
            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v1
              with:
                credentials_json: ${{ secrets.GCP_BACKEND_KEY }}

            # x. Set up GCP SDK
            - name: Set up GCP SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                project_id: indigo-skyline-467604-d6
                
            # 2. Test GCP Auth
            # The following block tests GCP authentication and bucket access.
            # Uncomment to use for debugging or verification.
            #
            # - name: Test GCP Auth
            #   run: |
            #     gcloud auth list
            #     gcloud config list
            #     ##Test bucket access
            #     gsutil ls gs://backend-static-hosting
            #     gsutil ls gs://backend-static-hosting/backend
                                    
            # 3. COnfiguring Docker to use GCloud
            -   name: Configure Docker to use gcloud
                run: |
                    gcloud config set project indigo-skyline-467604-d6
                    gcloud auth configure-docker asia-south2-docker.pkg.dev --quiet

            # 4. Build and push Docker image to GCR
            -   name: Build and Push Docker Image
                run: |
                    docker build -t asia-south2-docker.pkg.dev/indigo-skyline-467604-d6/backend-repo/backend:latest ./backend
                    docker push asia-south2-docker.pkg.dev/indigo-skyline-467604-d6/backend-repo/backend:latest
            
            # 5. Deploy to Cloud Run
            -   name: Deploy to Cloud Run
                run: |
                    gcloud run deploy backend-service \
                    --image asia-south2-docker.pkg.dev/indigo-skyline-467604-d6/backend-repo/backend:latest \
                    --platform managed \
                    --region asia-south2 \
                    --port 5000 \
                    --allow-unauthenticated
            
            # upload backend files to GCS
            -   name: Upload Backend to GCS
                uses: google-github-actions/upload-cloud-storage@v2
                with:
                    path: './backend'  # Target backend folder
                    destination: backend-static-hosting/backend
                    parent: false
                    cacheControl: 'public, max-age=3600, immutable'
                    process_gcloudignore: false  # Do not process .gcloudignore file
            # 6. Verify sync
            - run: gsutil ls -r gs://backend-static-hosting/backend

                
                