name: Deploy Frontend to GCS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Google Cloud SDK with authentication
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: indigo-skyline-467604-d6
          export_default_credentials: true
      # 3. Upload frontend files to GCS
      - name: Upload Frontend to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: './frontend'  # Target frontend folder
          destination: 'gs://frontend-static-hosting/frontend'
          parent: false
          predefinedAcl: 'publicRead'
          headers: 'Cache-Control=public, max-age=3600'
          process_gcloudignore: false

      # 4. Verify sync
      - run: gsutil ls -r gs://frontend-static-hosting/frontend
      - name: Test GCP Auth
        run: |
          gcloud auth list
          gcloud config list
          #Test bucket access
          gsutil ls gs://frontend-static-hosting
