name: Deploy Frontend to GCS
on:
  push:
    branches: [ 'main' ]
    paths: [ 'frontend/**' ] # Trigger on changes to the frontend directory
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Allow reading the repository contents
      id-token: write  # Allow generating an ID token for GCP authentication

    steps:
      - name: Test GCP Auth
        run: |
          gcloud auth list
          gcloud config list
          ##Test bucket access
          gsutil ls gs://frontend-static-hosting
          gsutil ls gs://frontend-static-hosting/frontend
      # 1. Checkout code
      - uses: actions/checkout@v4
      # 2. Set up legacy authentication for GCP using JSON key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_FRONTEND_KEY }}
    
      # 3. Upload frontend files to GCS
      - name: Upload Frontend to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: './frontend'  # Target frontend folder
          destination: frontend-static-hosting/frontend
          parent: false
          cacheControl: 'public, max-age=3600, immutable'
          process_gcloudignore: false  # Do not process .gcloudignore file

      # 4. Verify sync
      - run: gsutil ls -r gs://frontend-static-hosting/frontend
