# ci-cd.yml
name: Deploy Frontend to GCS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Upload ONLY frontend files to GCS
      - uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: './frontend'  # Key change: Target frontend folder
          destination: 'gs://frontend-static-hosting/frontend'
          credentials: ${{ secrets.GCP_SA_KEY }}
          # Optional: Set cache control for assets
          predefinedAcl: 'publicRead'
          metadata: 'Cache-Control=public, max-age=3600'
